# Introduction {#sec-intro .unnumbered}

Hello! I'm Jonathan, and I want to teach you time series analysis I have designed this website to accompany the University of Chicago course ADSP 31006 "Time Series Analysis and Forecasting". Although the course will mostly be taught in a traditional lecture format, I would like to use this website to provide backing material for the lectures.

## Recommended textbooks {#sec-referencetexts}

Unlike [my statistics course website](https://adsp-stats.github.io), I do *not* intend that this course website be considered the principle text for the class. We will have two primary textbooks (described below), and the notes in these pages *supplement* the readings without *replacing* the readings.

 *  *Forecasting: Principles and Practice* 3rd edition, by Rob Hyndman and George Athanasopoulos

    This book is [freely available](https://otexts.com/fpp3/) and one of our two major reference sources. The book relies heavily on R code using the `tidyverse` constellation of packages and the new `fable` package written by the authors, which interleaves specifically with the `tsibble` package. Readers who prefer base R may instead read the book's [second edition](https://otexts.com/fpp3/) (also freely available), and readers who prefer Python will benefit from the new [Python edition](https://otexts.com/fpppy/) (also freely available).
    
 *  *Practical Time Series Analysis*, by Aileen Nielsen

    This is the second of our two major reference sources. In contrast to the Hyndman and Athanasopoulos textbook, Nielsen includes more on-the-job tips about working with real datasets, structuring and storing the data, and putting forecasting models into production. She uses a combination of R (using the less-common `data.table` environment) and Python examples, and describes time series analysis from both a statistical and a machine learning perspective.
    
 *  *Time Series Analysis: Forecasting and Control* 5th edition, by George Box, et al.

    One of the classic texts in the field. Box and his co-authors have introduced and refined (over several decades) the best all-purpose textbook from a purely statistical perspective. They spend less time discussing programming considerations or machine learning models.

## How these notes were made

I assembled these notes using [Quarto](https://quarto.org), a publishing system built around the Pandoc markdown language. I wrote all the code backing these notes in [R](https://cran.r-project.org), and alongside every figure or table you can find the corresponding R code.

Neither the text nor the R code in these notes were generated by AI tools: for better and worse the opinions expressed here are my own, and the I've described these concepts in my own voice.^[AI assistance was used to brainstorm case studies and examples, and to help with the layout and coding of the website itself.] Complaints can be submitted [here](https://chatgpt.com).